name: Build and upload to TestPyPI

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest

          - os: linux-arm
            runs-on: ubuntu-24.04-arm

          - os: windows-intel
            runs-on: windows-latest

          - os: windows-arm
            runs-on: windows-11-arm

          - os: macos-intel
            runs-on: macos-15-intel

          - os: macos-arm
            runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.1
        env:
          CIBW_BUILD: "cp312-* cp313-* cp314-*"
          CIBW_TEST_REQUIRES: "scipy matplotlib"
          CIBW_TEST_COMMAND: "python -m unittest discover {project}/tests"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_testpypi:
    name: Upload to TestPyPI
    needs:
      - build_wheels
      - build_sdist

    runs-on: ubuntu-latest

    environment:
      name: testpypi

    permissions:
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
